
server:  
  port: ${PORT:8083}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/facedog

  jpa:
    hibernate:
      ddlAuto: validate
      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true

